Fix links and typos, reformat code, make every channel follow the template
rcarubbi/awesome-brazilian-youtubers pull request #3
Opened 2024-06-29 18:42 UTC by Kazevic

Reformatei o Markdown e HTML, troquei uns links HTTP por HTTPS (e corrigi links quebrados), fiz a listagem de YouTubers de fato seguir o modelo, deixei alguns textos mais concisos e gramaticamente corretos e mais outras mudanças.

2024-06-29 21:53 UTC, rcarubbi requested changes
eu coloquei diversos comentarios sobre quebras de linhas mas aparentemente eles nao causam nenhuma diferença quando o markdown é renderizado. Então você pode desconsiderá-los. Acho que somente o a craseado e as imagens que precisam ser revistos. 
Obrigado por contribuir! Fiquei mto feliz em saber que alguem achou que valia a pena perder tempo melhorando esta página! haha abraço!

2024-06-29 21:53 UTC, rcarubbi commented on CODE_OF_CONDUCT.md
> +corretivas apropriadas e justas em resposta a quaisquer instâncias de comportamento inaceitável.
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CODE_OF_CONDUCT.md
> +códigos, edições wiki, problemas e outras contribuições que não estejam alinhadas com este Código de Conduta, ou banir
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CODE_OF_CONDUCT.md
> +projeto ou sua comunidade. Exemplos de representação de um projeto ou comunidade incluem o uso de um endereço de e-mail
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CODE_OF_CONDUCT.md
> +projeto em rcarubbi@gmail.com. Todas as reclamações serão analisadas e investigadas e resultarão em uma resposta que se
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CODE_OF_CONDUCT.md
> +temporárias, ou permanentes conforme determinado por outros membros da liderança do projeto.
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CONTRIBUTING.md
> +coleção"_. [O que é awesome?](https://github.com/sindresorhus/awesome/blob/main/awesome.md#only-awesome-is-awesome)
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CONTRIBUTING.md
> +destaque: `Open Source Friday`, `GitHub Satellite 2020 - Work`, `Public Roadmap`, `GitHub Artic Code Vault`.
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CONTRIBUTING.md
> +abaixo.**
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CONTRIBUTING.md
> +  semanais). Se o canal não satisfizer um destes requerimentos, remova o distintivo. Mais informações
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CONTRIBUTING.md
> +  armazenagem de repositórios.
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CONTRIBUTING.md
> +  videos diariamente com tutoriais de tecnologia em geral. Estes tutoriais incluem proteção à sua empresa, busca de
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CONTRIBUTING.md
> +  vulnerabilidades, uso de GitHub Actions e mais. Também tem playlists muito úteis onde você pode encontrar palestras
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on CONTRIBUTING.md
> +  de profissionais que te ensinam diversos tópicos.
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on README.md
> +> Assista a tutoriais de YouTubers que ensinam sobre tecnologia.
eu acredito que este "a" seja craseado

2024-06-29 21:53 UTC, rcarubbi commented on README.md
> +próprias listas de Awesome YouTubers de tecnologia em outros idiomas. **Abaixo você pode ver todos os repositórios
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on README.md
> +Java… Inclusive, muitos YouTubers ensinam sobre frameworks destas linguagens. Não apenas linguagens de programação, mas
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on README.md
> +outros assuntos relacionados a programação também. Você pode encontrar tanto tutoriais práticos como teóricos.
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on badges/badge-pt-br.svg
nao entendi qual é a mudança na imagem

2024-06-29 21:53 UTC, rcarubbi commented on badges/badge-semanal.svg
nao entendi qual é a mudança na imagem

2024-06-29 21:53 UTC, rcarubbi commented on badges/badge-verificado.svg
nao entendi qual é a mudança na imagem

2024-06-29 21:53 UTC, rcarubbi commented on badges/logo.svg
nao entendi qual é a mudança na imagem

2024-06-29 21:53 UTC, rcarubbi commented on badges/README.md
> +YouTube verificados [aqui](https://support.google.com/youtube/answer/3046484?hl=pt).
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on badges/README.md
> +concedidos a um YouTuber. Estes distintivos apenas servem como informações adicionais para você enquanto navega através
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on badges/README.md
> +desta lista.
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on README.md
> +destaque: `Curso de HTML5 Completo e GRÁTIS`, `Curso de Lógica de Programação`, `Curso de PHP para Iniciantes`, `Curso de Photoshop CC`, `Curso de Banco de Dados MySQL`, `Curso de Python 3 - Mundo 1:
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on README.md
> +Playlists em
por que a quebra de linha aqui?

2024-06-29 21:53 UTC, rcarubbi commented on README.md
> +destaque: `Clean Code - Desvendando Livros`, `Tecnologias por trás dos Games`, `Tech Hour 2022`, `O Que Programadores Fazem?`, `Compilado Podcast`.
por que a quebra de linha aqui?

2024-06-30 03:45 UTC, Kazevic commented
> eu coloquei diversos comentarios sobre quebras de linhas mas aparentemente eles nao causam nenhuma diferença quando o markdown é renderizado. Então você pode desconsiderá-los. Acho que somente o a craseado e as imagens que precisam ser revistos. Obrigado por contribuir! Fiquei mto feliz em saber que alguem achou que valia a pena perder tempo melhorando esta página! haha abraço!

Opa, não achei a parte do craseado, mas sobre os outros dois:

Nas imagens, a mudança foi no código, que, se me lembro bem, foi reformatado, teve uma parte inútil retirada e troquei o link HTTP para HTTPS (não os dois, pois o link em si da imagem não funciona como HTTPS).

Quanto às quebras de linhas, há uma estando acima de 120 caracteres ou após uma pontuação ou conjunção quando se aproxima do limite. Ela funciona como um espaço, então altera em nada além de legibilidade para quem edita.

2024-06-30 03:54 UTC, Kazevic commented
Saindo um pouco do tópico, contribuir para o repositório me ensinou bastante sobre a minha IDE (WebStorm da JetBrains) KKKK. Ainda sou iniciante, então esse tipo de coisa acontece. Não tenho tido o tempo de dar grandes saltos no meu conhecimento de programação, mas pelo menos fico feliz por contribuir para tantos repositórios (devo ter mais de 10 forks no perfil, todas com uma PR ou então com uma commit que creio que o repositório original não aceitaria).

2024-06-30 04:37 UTC, merged